### ISSUE TITLE
[Requesting Details] Tags pages not populating properly

### ISSUE THREAD

**Issue by Vaibhav** [oct8l/crab-example#1]
Hey, Is this the repo where you'd like the fix the big you mentioned at [BountySource](https://www.bountysource.com/issues/56151052-tags-pages-not-populating-properly)? I don't think the issue is for the template repo (where you opened the issue), since that is a template.

The fix should be implemented in your own repo, so is it this repo or another one? 

Let me know!

**Comment by ghost** [comment]
The issue has since been fixed. It was in fact an issue with the theme repo "crab" that was listed on BountySource. https://github.com/thomasheller/crab
The fix is in my repo of crab, I currently have a pull request and the pages for this repo need to be updated with my new changes. https://github.com/thomasheller/crab/pull/13

**Comment by oct8l** [comment]
@Vaibhav yeah this was a request for the template to be corrected, I wasn't sure how it would be implemented but @drowssaPdnAemanresU submitted a PR that had this fix and a few others in there.

Sorry for any confusion on where the fix was needed!

**Comment by ghost** [comment]
@oct8l , you'll still need to rebuild the website in this repo though. There are a few bugs that have since been patched.

**Comment by oct8l** [comment]
There we go, now it's all up-to-date. I appreciate everything again.
